### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asotronot**
Created a Development section in README.md file for https://github.com/freedomotic/fd-vue-webapp

### CODE REVIEW

**Comment by P3trur0** [comment]
HI @asotronot, as you might see now your PR has conflicts with the current state of `README.md` because of the scaffolding just pushed on master branch.

Could you please revisit your own contribution and make it working with the new version of the file?

Please, stay with a single commit!

Thank you!

**Comment by asotronot** [comment]
Fixed the conflict. Thanks :)

**Comment by P3trur0** [comment]
@asotronot thank you. Could you please squash your commit too?

**Comment by asotronot** [comment]
Hey ! Did you guys enable the feature for merge squashing for this repository ? I am trying to find the option where it let me squash the commits but I can't see where it is.

When I use git log on bash, I only see the commits by other people that have been approved before.

**Comment by P3trur0** [comment]
Hi @asotronot I guess it is enough to perform a squash on your branch. Then the PR should be fixed automatically.

**Pull request closed without merging**
